version: '1'
services:
   backend:
    container_name: chat_node
    build:
      context: ./server
      dockerfile: DockerFile
    image: akhilchennu/chat_node
    ports:
      - 3001:3001
   frontend:
    container_name: chat_react
    build: 
       context: ./client
       dockerfile: DockerFile
    image: akhilchennu/chat_react
    ports:
     - 3000:3000
    depends_on:
     - backend
   redis:
    container_name: chat_redis
    image: redis
    ports:
      - 6379:6379
#to check if any error occurs =>docker-compose config .It will return file content if no erros
#to build the docker file docker-compose build      
#docker-compose up -d for running the docker compose file