version: '1'
services:
   frontend:
    container_name: chat_react
    build: 
       context: ./client
       dockerfile: DockerFile
    image: akhilchennu/chat_react
    ports:
     - 3000:3000
    depends_on:
     - backend
   redis:
    container_name: chat_redis
    image: redis
    ports:
      - 6379:6379
    command: ["redis-server"]
   backend:
    container_name: chat_node
    build:
      context: ./server
      dockerfile: DockerFile
    image: akhilchennu/chat_node
    ports:
      - 3001:3008 #node application running on 3008 port in the container as we have configured env local in DOCKERFILE it is taking from .env_local and we are hosting it on 3001 port in our server/machine
    depends_on:
      - redis
#to check if any error occurs =>docker-compose config .It will return file content if no erros
#to build the docker file docker-compose build      
#docker-compose up -d for running the docker compose file
#docker exec -it 5ae4c4391c4b redis-cl for redis cli inside docker container